spring:
  application:
    name: microservice-client
    server:
    port: 8072
eureka:
  client:
    register-with-eureka: true
    fatchRegistry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
      instance:
      hostname: localhost